# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generates a matrix containing every possible score combination
#' where each row sum is equal to the provided esf order.
#'
#' @param p The esf order of the elementary symmetric function.
#' @param M The number of items
#' @return Every possible score combination as a matrix
poly_idx_cpp <- function(p, M) {
    .Call('_rpcmtree_poly_idx_cpp', PACKAGE = 'rpcmtree', p, M)
}

